defaults: &defaults
  contact_email: test@example.net
  exception_email: test@example.net
  twitter_user: andrzejkrzywda
  twitter_list: drug-org-pl
  twitter_url: http://twitter.com/andrzejkrzywda/drug-org-pl

development:
  <<: *defaults
  maps_api_key: ABQIAAAARxhDyCAgkxaRS-btAXEOmRS1rKNKCajL_OjXVxcRqG-4FK8BDRRM9BBR1vD4b0biuXxliOmiRrL1hQ

test:
  <<: *defaults
  maps_api_key: ABQIAAAARxhDyCAgkxaRS-btAXEOmRS1rKNKCajL_OjXVxcRqG-4FK8BDRRM9BBR1vD4b0biuXxliOmiRrL1hQ

production:
  <<: *defaults
  maps_api_key: ABQIAAAARxhDyCAgkxaRS-btAXEOmRTYcVd6WlBKPyXZXreVpEGKzqDr8hTOsV_H95tbwbjuwVYng7sEbK-pvA
