defaults: &defaults
  contact_email: test@example.net
  exception_email: test@example.net
  twitter_user: andrzejkrzywda
  twitter_list: drug-org-pl
  twitter_url: http://twitter.com/andrzejkrzywda/drug-org-pl

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
